### ISSUE TITLE
Make data mapping easier using UI

### ISSUE THREAD

**Issue by jvsoest** [maastroclinic/DataFAIRifier#14]
This is possible in Protege, but is an ontop-proprietary solution.

The question is how we can make an R2RML mapping using a graphical tool which helps in selecting the right tables/columns/values.

**Comment by bpmweel** [comment]
We discussed starting out with a survey of existing tools.

The target audience for this tool would be a clinical physicist with basic programming experience (e.g. matlab scripting).

If there is no tool we will need to create something. The first idea is at least a tool where they can select in which table and column a specific target is located in the database.

**Comment by MartineDeVos** [comment]
Maybe these tools are interesting to explore:
http://usc-isi-i2.github.io/karma/
http://ceur-ws.org/Vol-1690/paper62.pdf

**Comment by jvsoest** [comment]
Done in Jupyter Notebooks
