### ISSUE TITLE
Adapt memory threshold GraphDB in Docker

### ISSUE THREAD

**Issue by MartineDeVos** [maastroclinic/DataFAIRifier#25]
The RAM memory threshold (1 GB) seems to be limiting loading RDF triples in GraphDB.
->  increase threshold

**Comment by MartineDeVos** [comment]
This could be a reason to use Virtuoso, as it allows querying virtual RDF graphs (i.e. views) which is more memory efficient

**Comment by jvsoest** [comment]
Can be adapted by using different environment variables, e.g.:
GDB_HEAP_SIZE=2g
GDB_MIN_MEM=1g
GDB_MAX_MEM=2g
